namespace Adr.Semantics.Mappers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Adr.Semantics.Models;

    /// <summary>
    /// Renders a collection of <see cref="GlossaryModel"/> entries as a Markdown list.
    /// </summary>
    public static class GlossaryMarkdownListMapper
    {
        private const string Header =
            "---\n"
            + "title: Connected Services Glossary of Terms\n"
            + "---\n"
            + "\n"
            + "<!--\n"
            + "This glossary was generated from the ADR semantics server API.\n"
            + "Do not edit this file directly. Retrieve the current markdown from the web API endpoint.\n"
            + "-->\n"
            + "\n";

        /// <summary>
        /// Renders the given glossary entries as a Markdown document.
        /// </summary>
        /// <param name="entries">The glossary entries to render.</param>
        /// <returns>A Markdown string ready to be written to a file.</returns>
        public static string Map(IEnumerable<GlossaryModel> entries)
        {
            var ordered = (entries ?? Enumerable.Empty<GlossaryModel>())
                .Where(e => !string.IsNullOrWhiteSpace(e?.Term))
                .Where(e => e.PublishToDevHub && e.VerifiedDefinitionFlag)
                .OrderBy(e => e.Term, StringComparer.OrdinalIgnoreCase)
                .ToList();

            var stringBuilder = new StringBuilder();
            stringBuilder.Append(Header);

            foreach (var entry in ordered)
            {
                var categories = string.Join(", ", (entry.Categories ?? Enumerable.Empty<string>())
                    .Where(c => !string.IsNullOrWhiteSpace(c))
                    .Select(c => c.Trim()));

                stringBuilder
                    .Append("## ")
                    .Append(entry.Term.Trim())
                    .Append("\n\n")
                    .Append(entry.Definition)
                    .Append("\n\n");

                if (!string.IsNullOrWhiteSpace(categories))
                {
                    stringBuilder
                        .Append("Categories: ")
                        .Append(categories)
                        .Append("\n\n");
                }
            }

            return stringBuilder.ToString();
        }
    }
}
