namespace Adr.Semantics.Mappers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Adr.Semantics.Models;

    /// <summary>
    /// Renders a collection of <see cref="GlossaryModel"/> entries as a Markdown list.
    /// </summary>
    public static class GlossaryMarkdownListMapper
    {
        private const string Header =
            "---\n"
            + "title: Connected Services Glossary of Terms list\n"
            + "---\n"
            + "\n"
            + "<!--\n"
            + "This glossary was generated from the ADR semantics server API.\n"
            + "Do not edit this file directly. Retrieve the current markdown from the web API endpoint.\n"
            + "-->\n"
            + "\n";

        /// <summary>
        /// Renders the given glossary entries as a Markdown document.
        /// </summary>
        /// <param name="entries">The glossary entries to render.</param>
        /// <returns>A Markdown string ready to be written to a file.</returns>
        public static string Map(IEnumerable<GlossaryModel> entries)
        {
            var ordered = (entries ?? Enumerable.Empty<GlossaryModel>())
                .Where(e => !string.IsNullOrWhiteSpace(e?.Term))
                .Where(e => e.PublishToDevHub && e.VerifiedDefinitionFlag)
                .OrderBy(e => e.Term, StringComparer.OrdinalIgnoreCase)
                .ToList();

            var groupedEntries = ordered
                .GroupBy(entry => GetSectionLetter(entry.Term))
                .OrderBy(group => group.Key == "#" ? "ZZZ" : group.Key, StringComparer.Ordinal)
                .ToList();

            var stringBuilder = new StringBuilder();
            stringBuilder.Append(Header);

            if (groupedEntries.Any())
            {
                var links = groupedEntries
                    .Select(group => $"[{group.Key}](#{GetSectionId(group.Key)})");
                stringBuilder.Append(string.Join(" | ", links)).Append("\n\n");
            }

            foreach (var group in groupedEntries)
            {
                stringBuilder
                    .Append("## ")
                    .Append(group.Key)
                    .Append(" {#")
                    .Append(GetSectionId(group.Key))
                    .Append("}\n\n");

                foreach (var entry in group)
                {
                    var keywords = string.Join(
                        ", ",
                        (entry.Keywords ?? Enumerable.Empty<string>())
                            .Where(c => !string.IsNullOrWhiteSpace(c))
                            .Select(c => c.Trim())
                    );

                    stringBuilder
                        .Append("### ")
                        .Append(entry.Term.Trim())
                        .Append(" {#")
                        .Append(GetTermId(entry.StaticId, entry.Term))
                        .Append("}\n\n")
                        .Append(entry.Definition)
                        .Append("\n\n");

                    if (!string.IsNullOrWhiteSpace(keywords))
                    {
                        stringBuilder.Append("Keywords: ").Append(keywords).Append("\n\n");
                    }

                    if (!string.IsNullOrWhiteSpace(entry.Context))
                    {
                        stringBuilder.Append("Context: ").Append(entry.Context).Append("\n\n");
                    }
                }
            }

            return stringBuilder.ToString();
        }

        private static string GetSectionLetter(string term)
        {
            var firstCharacter = term?.Trim().FirstOrDefault() ?? '\0';
            if (char.IsLetter(firstCharacter))
            {
                return char.ToUpperInvariant(firstCharacter).ToString();
            }

            return "#";
        }

        private static string GetSectionId(string sectionLetter)
        {
            return sectionLetter == "#"
                ? "terms-other"
                : $"terms-{sectionLetter.ToLowerInvariant()}";
        }

        private static string GetTermId(string staticId, string term)
        {
            var normalizedId = staticId?.Trim();
            if (!string.IsNullOrWhiteSpace(normalizedId))
            {
                return $"term-{normalizedId.ToLowerInvariant()}";
            }

            // Fallback only for unexpected records missing StaticId.
            return $"term-{term.Trim().ToLowerInvariant()}";
        }
    }
}
