namespace Adr.Semantics.Mappers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Adr.Semantics.Models;

    /// <summary>
    /// Renders a collection of <see cref="GlossaryModel"/> entries as a Markdown list.
    /// </summary>
    public static class GlossaryMarkdownListMapper
    {
        private const string Header =
            "---\n"
            + "title: Connected Services Glossary of Terms list\n"
            + "---\n"
            + "\n"
            + "<!--\n"
            + "This glossary was generated from the ADR semantics server API.\n"
            + "Do not edit this file directly. Retrieve the current markdown from the web API endpoint.\n"
            + "-->\n"
            + "\n";

        /// <summary>
        /// Renders the given glossary entries as a Markdown document.
        /// </summary>
        /// <param name="entries">The glossary entries to render.</param>
        /// <returns>A Markdown string ready to be written to a file.</returns>
        public static string Map(IEnumerable<GlossaryModel> entries)
        {
            var ordered = (entries ?? Enumerable.Empty<GlossaryModel>())
                .Where(e => !string.IsNullOrWhiteSpace(e?.Term))
                .Where(e => e.PublishToDevHub && e.VerifiedDefinitionFlag)
                .OrderBy(e => e.Term, StringComparer.OrdinalIgnoreCase)
                .ToList();

            var groupedByLetter = ordered
                .GroupBy(entry => GetSectionLetter(entry.Term))
                .OrderBy(group => group.Key == "#" ? "ZZZ" : group.Key, StringComparer.Ordinal)
                .ToList();

            var stringBuilder = new StringBuilder();
            stringBuilder.Append(Header);

            if (groupedByLetter.Any())
            {
                var links = groupedByLetter
                    .Select(group => $"[{group.Key}](#{GetSectionId(group.Key)})");
                stringBuilder.Append(string.Join(" | ", links)).Append("\n\n");
            }

            foreach (var letterGroup in groupedByLetter)
            {
                stringBuilder
                    .Append("## ")
                    .Append(letterGroup.Key)
                    .Append(" {#")
                    .Append(GetSectionId(letterGroup.Key))
                    .Append("}\n\n");

                foreach (var entry in letterGroup)
                {
                    var keywords = string.Join(
                        ", ",
                        (entry.Keywords ?? Enumerable.Empty<string>())
                            .Where(c => !string.IsNullOrWhiteSpace(c))
                            .Select(c => c.Trim())
                    );

                    stringBuilder
                        .Append("### ")
                        .Append(entry.Term.Trim())
                        .Append(" {#")
                        .Append(GetTermId(entry.StaticId, entry.Name))
                        .Append("}\n\n")
                        .Append(entry.Definition)
                        .Append("\n\n");

                    if (!string.IsNullOrWhiteSpace(keywords))
                    {
                        stringBuilder.Append("Keywords: ").Append(keywords).Append("\n\n");
                    }

                    if (!string.IsNullOrWhiteSpace(entry.Context))
                    {
                        var contextText = entry.Context.Trim();
                        var urls = ExtractUrls(entry.Citations);

                        if (urls.Count > 0)
                        {
                            stringBuilder.Append("Context: ");

                            for (int i = 0; i < urls.Count; i++)
                            {
                                if (i > 0)
                                {
                                    stringBuilder.Append(", ");
                                }

                                stringBuilder
                                    .Append("[")
                                    .Append(contextText)
                                    .Append("](")
                                    .Append(urls[i])
                                    .Append(")");
                            }

                            stringBuilder.Append("\n\n");
                        }
                        else
                        {
                            stringBuilder.Append("Context: ").Append(contextText).Append("\n\n");
                        }
                    }
                }
            }

            return stringBuilder.ToString();
        }

        private static string GetSectionLetter(string term)
        {
            var firstCharacter = term?.Trim().FirstOrDefault() ?? null;
            if (firstCharacter.HasValue && char.IsLetter(firstCharacter.Value))
            {
                return char.ToUpperInvariant(firstCharacter.Value).ToString();
            }

            return "#";
        }

        private static string GetSectionId(string sectionLetter)
        {
            return sectionLetter == "#"
                ? "terms-other"
                : $"terms-{sectionLetter.ToLowerInvariant()}";
        }

        private static string GetTermId(string staticId, string name)
        {
            var normalizedId = staticId?.Trim();
            if (!string.IsNullOrWhiteSpace(normalizedId))
            {
                return $"term-{normalizedId.ToLowerInvariant()}";
            }

            // Fallback only for unexpected records missing StaticId.
            return $"term-{name.ToLowerInvariant()}";
        }

        private static List<string> ExtractUrls(string text)
        {
            var urls = new List<string>();
            if (string.IsNullOrWhiteSpace(text))
            {
                return urls;
            }

            var trimmed = text.Trim();

            // Split by whitespace and newlines to find potential URLs
            var parts = trimmed.Split(new[] { ' ', '\n', '\r', '\t' }, StringSplitOptions.RemoveEmptyEntries);

            foreach (var part in parts)
            {
                if (IsValidUrl(part))
                {
                    urls.Add(part);
                }
            }

            return urls;
        }

        private static bool IsValidUrl(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return false;
            }

            if (!Uri.TryCreate(text, UriKind.Absolute, out var uri))
            {
                return false;
            }

            // Only accept http and https schemes
            if (uri.Scheme != Uri.UriSchemeHttp && uri.Scheme != Uri.UriSchemeHttps)
            {
                return false;
            }

            // Host must contain at least one dot (`example.com` is valid, `example` and `Data` are not)
            if (!uri.Host.Contains('.'))
            {
                return false;
            }

            return true;
        }
    }
}
