site_name: "Connected Services Glossary"
site_description: "Turning information into understanding"
docs_dir: "Documentation/Devhub/Pages"
repo_url: "https://github.com/bcgov/adr"
edit_uri: edit/dev/Documentation/Devhub/Pages/
nav:
  - Introduction: index.md
  - Connected Services Glossary of Terms: glossary.md
  - Scoping Rules: scoping-rules.md
plugins:
  - techdocs-core
  - git-revision-date-localized
markdown_extensions:
  - attr_list
  - md_in_html
