site_name: "Connected Services Glossary"
site_description: "Standards, dictionaries, and glossaries for authoritative data registers."
docs_dir: "Documentation/Devhub/Pages"
repo_url: "https://github.com/bcgov/adr"
edit_uri: edit/dev/Documentation/Devhub/Pages/
nav:
  - Introduction: index.md
  - Configuration: configuration.md
  - Tips and tricks: tips-and-tricks.md
  - About us: about-us.md
  - Connected Services Glossary of Terms table: glossary.md
  - Connected Services Glossary of Terms list: glossary-list.md
plugins:
  - techdocs-core
  - git-revision-date-localized
markdown_extensions:
  - attr_list
  - md_in_html
