/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ministries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single ministry by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A ministry object */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ministry"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Representation of a government ministry */
        Ministry: {
            /**
             * Format: uuid
             * @description Unique identifier (UUID) for the ministry
             */
            id: string;
            /** @description Full ministry name */
            name: string;
            /** @description Short acronym for the ministry (may be empty) */
            acronym: string;
            /**
             * Format: date
             * @description Date ministry became effective (nullable)
             */
            effectiveDate?: string | null;
            /**
             * Format: date
             * @description Date ministry was retired (nullable)
             */
            retirementDate?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
