// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getAllPublicBodies, getPublicBodyById, getPublicBodyTypes, type Options } from '../sdk.gen';
import type { GetAllPublicBodiesData, GetAllPublicBodiesResponse, GetPublicBodyByIdData, GetPublicBodyByIdError, GetPublicBodyByIdResponse, GetPublicBodyTypesData, GetPublicBodyTypesResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAllPublicBodiesQueryKey = (options?: Options<GetAllPublicBodiesData>) => createQueryKey('getAllPublicBodies', options);

export const getAllPublicBodiesOptions = (options?: Options<GetAllPublicBodiesData>) => queryOptions<GetAllPublicBodiesResponse, DefaultError, GetAllPublicBodiesResponse, ReturnType<typeof getAllPublicBodiesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllPublicBodies({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllPublicBodiesQueryKey(options)
});

export const getPublicBodyByIdQueryKey = (options: Options<GetPublicBodyByIdData>) => createQueryKey('getPublicBodyById', options);

export const getPublicBodyByIdOptions = (options: Options<GetPublicBodyByIdData>) => queryOptions<GetPublicBodyByIdResponse, GetPublicBodyByIdError, GetPublicBodyByIdResponse, ReturnType<typeof getPublicBodyByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPublicBodyById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPublicBodyByIdQueryKey(options)
});

export const getPublicBodyTypesQueryKey = (options?: Options<GetPublicBodyTypesData>) => createQueryKey('getPublicBodyTypes', options);

export const getPublicBodyTypesOptions = (options?: Options<GetPublicBodyTypesData>) => queryOptions<GetPublicBodyTypesResponse, DefaultError, GetPublicBodyTypesResponse, ReturnType<typeof getPublicBodyTypesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPublicBodyTypes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPublicBodyTypesQueryKey(options)
});
