/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Ministries API (example)
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Get a single ministry by id
 */
export const getMinistriesIdParams = zod.object({
  "id": zod.uuid()
})

export const getMinistriesIdResponse = zod.object({
  "id": zod.uuid().describe('Unique identifier (UUID) for the ministry'),
  "name": zod.string().describe('Full ministry name'),
  "acronym": zod.string().describe('Short acronym for the ministry (may be empty)'),
  "effectiveDate": zod.iso.date().nullish().describe('Date ministry became effective (nullable)'),
  "retirementDate": zod.iso.date().nullish().describe('Date ministry was retired (nullable)')
}).describe('Representation of a government ministry')
