// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getAllDictionaries, getAllGlossary, getGlossaryEntryByTerm, type Options } from '../sdk.gen';
import type { GetAllDictionariesData, GetAllDictionariesResponse, GetAllGlossaryData, GetAllGlossaryResponse, GetGlossaryEntryByTermData, GetGlossaryEntryByTermError, GetGlossaryEntryByTermResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAllDictionariesQueryKey = (options?: Options<GetAllDictionariesData>) => createQueryKey('getAllDictionaries', options);

export const getAllDictionariesOptions = (options?: Options<GetAllDictionariesData>) => queryOptions<GetAllDictionariesResponse, DefaultError, GetAllDictionariesResponse, ReturnType<typeof getAllDictionariesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllDictionaries({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllDictionariesQueryKey(options)
});

export const getAllGlossaryQueryKey = (options?: Options<GetAllGlossaryData>) => createQueryKey('getAllGlossary', options);

export const getAllGlossaryOptions = (options?: Options<GetAllGlossaryData>) => queryOptions<GetAllGlossaryResponse, DefaultError, GetAllGlossaryResponse, ReturnType<typeof getAllGlossaryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllGlossary({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllGlossaryQueryKey(options)
});

export const getGlossaryEntryByTermQueryKey = (options: Options<GetGlossaryEntryByTermData>) => createQueryKey('getGlossaryEntryByTerm', options);

export const getGlossaryEntryByTermOptions = (options: Options<GetGlossaryEntryByTermData>) => queryOptions<GetGlossaryEntryByTermResponse, GetGlossaryEntryByTermError, GetGlossaryEntryByTermResponse, ReturnType<typeof getGlossaryEntryByTermQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlossaryEntryByTerm({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlossaryEntryByTermQueryKey(options)
});
