<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
        <EmbeddedResource Include="Assets\public_bodies.csv" />
        <EmbeddedResource Include="Assets\public body_types.csv" />
        <EmbeddedResource Include="Assets\public_bodies_parent_child.csv" />
    </ItemGroup>
</Project>
