/**
 * This file was auto-generated by openapi-typescript. It is included for
 * reference, but not used directly for schema validation.
 *
 * To generate:
 *
 * ```sh
 * npx openapi-typescript https://public-bodies.dev.api.gov.bc.ca/swagger/v1/swagger.json -o ./openapi-typescript-schema.d.ts
 * ```
 */

export interface paths {
  "/PublicBodies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          /** @description The requested API version */
          "api-version"?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["StringBaseResponseModel"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/PublicBodies/names": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          /** @description The requested API version */
          "api-version"?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PublicBodyNameModelIEnumerableBaseResponseModel"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/PublicBodies/types": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          /** @description The requested API version */
          "api-version"?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PublicBodyTypeModelIEnumerableBaseResponseModel"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    BaseAuditModel: {
      /**
       * Nullable<DateOnly>
       * Format: date
       */
      effectiveDate?: string | null;
      /**
       * Nullable<DateOnly>
       * Format: date
       */
      retirementDate?: string | null;
    };
    PublicBodyNameModel: components["schemas"]["BaseAuditModel"] & {
      id: string | null;
      staticId: string | null;
      name: string | null;
      acronym?: string | null;
      publicBodyTypeId?: string | null;
      publicBodyType?: components["schemas"]["PublicBodyTypeModel"];
    };
    /** BaseResponseModel<IEnumerable`1> */
    PublicBodyNameModelIEnumerableBaseResponseModel: {
      /** IEnumerable<PublicBodyNameModel> */
      payload: components["schemas"]["PublicBodyNameModel"][] | null;
      /** Format: date-time */
      datetimeRequested: string;
    };
    PublicBodyTypeModel: components["schemas"]["BaseAuditModel"] & {
      id: string | null;
      staticId: string | null;
      code: string | null;
      name: string | null;
      description?: string | null;
    };
    /** BaseResponseModel<IEnumerable`1> */
    PublicBodyTypeModelIEnumerableBaseResponseModel: {
      /** IEnumerable<PublicBodyTypeModel> */
      payload: components["schemas"]["PublicBodyTypeModel"][] | null;
      /** Format: date-time */
      datetimeRequested: string;
    };
    /** BaseResponseModel<String> */
    StringBaseResponseModel: {
      payload: string | null;
      /** Format: date-time */
      datetimeRequested: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
