// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAllPublicBodiesData, GetAllPublicBodiesResponses, GetPublicBodyByIdData, GetPublicBodyByIdErrors, GetPublicBodyByIdResponses, GetPublicBodyTypesData, GetPublicBodyTypesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getAllPublicBodies = <ThrowOnError extends boolean = false>(options?: Options<GetAllPublicBodiesData, ThrowOnError>) => (options?.client ?? client).get<GetAllPublicBodiesResponses, unknown, ThrowOnError>({ url: '/v1/PublicBodies', ...options });

export const getPublicBodyById = <ThrowOnError extends boolean = false>(options: Options<GetPublicBodyByIdData, ThrowOnError>) => (options.client ?? client).get<GetPublicBodyByIdResponses, GetPublicBodyByIdErrors, ThrowOnError>({ url: '/v1/PublicBodies/{id}', ...options });

export const getPublicBodyTypes = <ThrowOnError extends boolean = false>(options?: Options<GetPublicBodyTypesData, ThrowOnError>) => (options?.client ?? client).get<GetPublicBodyTypesResponses, unknown, ThrowOnError>({ url: '/v1/PublicBodies/types', ...options });
