// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5000' | (string & {});
};

export type AdrPublicBodiesModelsBaseAuditModel = {
    /**
     * Nullable<DateOnly>
     */
    recordCreatedDatetime?: string | null;
    /**
     * Nullable<DateOnly>
     */
    recordEndedDatetime?: string | null;
    recordCreatedUser?: string | null;
    recordEndedUser?: string | null;
};

/**
 * BaseResponseModel<PublicBodyHistoryModel>
 */
export type AdrPublicBodiesModelsBaseResponseModelAdrPublicBodiesModelsPublicBodyHistoryModel = {
    payload: AdrPublicBodiesModelsPublicBodyHistoryModel;
    datetimeRequested: string;
};

/**
 * BaseResponseModel<PublicBodyModel>
 */
export type AdrPublicBodiesModelsBaseResponseModelAdrPublicBodiesModelsPublicBodyModel = {
    payload: AdrPublicBodiesModelsPublicBodyModel;
    datetimeRequested: string;
};

/**
 * BaseResponseModel<IEnumerable`1>
 */
export type AdrPublicBodiesModelsBaseResponseModelSystemCollectionsGenericListAdrPublicBodiesModelsPublicBodyModel = {
    /**
     * IEnumerable<PublicBodyModel>
     */
    payload: Array<AdrPublicBodiesModelsPublicBodyModel> | null;
    datetimeRequested: string;
};

/**
 * BaseResponseModel<IEnumerable`1>
 */
export type AdrPublicBodiesModelsBaseResponseModelSystemCollectionsGenericListAdrPublicBodiesModelsPublicBodyParentChildModel = {
    /**
     * IEnumerable<PublicBodyParentChildModel>
     */
    payload: Array<AdrPublicBodiesModelsPublicBodyParentChildModel> | null;
    datetimeRequested: string;
};

/**
 * BaseResponseModel<IEnumerable`1>
 */
export type AdrPublicBodiesModelsBaseResponseModelSystemCollectionsGenericListAdrPublicBodiesModelsPublicBodyTypeModel = {
    /**
     * IEnumerable<PublicBodyTypeModel>
     */
    payload: Array<AdrPublicBodiesModelsPublicBodyTypeModel> | null;
    datetimeRequested: string;
};

export type AdrPublicBodiesModelsPublicBodyHistoryModel = {
    publicBodyId: string | null;
    /**
     * IEnumerable<PublicBodyModel>
     */
    publicBodies: Array<AdrPublicBodiesModelsPublicBodyModel> | null;
    /**
     * IEnumerable<PublicBodyParentChildModel>
     */
    relationships: Array<AdrPublicBodiesModelsPublicBodyParentChildModel> | null;
};

export type AdrPublicBodiesModelsPublicBodyModel = AdrPublicBodiesModelsBaseAuditModel & {
    id: string | null;
    staticId: string | null;
    publicBodyId?: string | null;
    businessIdSource?: string | null;
    businessIdValue?: string | null;
    name: string | null;
    acronym?: string | null;
    sector?: string | null;
    typeId?: string | null;
    /**
     * Nullable<DateOnly>
     */
    publicBodyEffectiveDate?: string | null;
    /**
     * Nullable<DateOnly>
     */
    publicBodyRetiredDate?: string | null;
};

export type AdrPublicBodiesModelsPublicBodyParentChildModel = AdrPublicBodiesModelsBaseAuditModel & {
    parentChildId: string | null;
    /**
     * Nullable<DateOnly>
     */
    actionDatetime?: string | null;
    parentUniqueId: string | null;
    childUniqueId: string | null;
    wasRenamed?: boolean;
    wasMerged?: boolean;
    wasSplit?: boolean;
    /**
     * Nullable<DateOnly>
     */
    publicBodyEffectiveDatetime?: string | null;
};

export type AdrPublicBodiesModelsPublicBodyTypeModel = AdrPublicBodiesModelsBaseAuditModel & {
    id: string | null;
    staticId: string | null;
    publicBodyTypeId?: string | null;
    name: string | null;
    shortName?: string | null;
    /**
     * Nullable<DateOnly>
     */
    typeEffectiveDatetime?: string | null;
    /**
     * Nullable<DateOnly>
     */
    typeRetiredDatetime?: string | null;
};

export type MicrosoftAspNetCoreHttpHttpValidationProblemDetails = MicrosoftAspNetCoreMvcProblemDetails & {
    /**
     * IDictionary<String>
     */
    errors?: {
        [key: string]: Array<string>;
    } | null;
    [key: string]: unknown;
};

export type MicrosoftAspNetCoreMvcProblemDetails = {
    type?: string | null;
    title?: string | null;
    /**
     * Nullable<Int32>
     */
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type GetAllPublicBodiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/PublicBodies';
};

export type GetAllPublicBodiesResponses = {
    /**
     * OK
     */
    200: AdrPublicBodiesModelsBaseResponseModelSystemCollectionsGenericListAdrPublicBodiesModelsPublicBodyModel;
};

export type GetAllPublicBodiesResponse = GetAllPublicBodiesResponses[keyof GetAllPublicBodiesResponses];

export type GetPublicBodyByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/PublicBodies/{id}';
};

export type GetPublicBodyByIdErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails | MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
};

export type GetPublicBodyByIdError = GetPublicBodyByIdErrors[keyof GetPublicBodyByIdErrors];

export type GetPublicBodyByIdResponses = {
    /**
     * OK
     */
    200: AdrPublicBodiesModelsBaseResponseModelAdrPublicBodiesModelsPublicBodyModel;
};

export type GetPublicBodyByIdResponse = GetPublicBodyByIdResponses[keyof GetPublicBodyByIdResponses];

export type GetPublicBodyTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/PublicBodies/types';
};

export type GetPublicBodyTypesResponses = {
    /**
     * OK
     */
    200: AdrPublicBodiesModelsBaseResponseModelSystemCollectionsGenericListAdrPublicBodiesModelsPublicBodyTypeModel;
};

export type GetPublicBodyTypesResponse = GetPublicBodyTypesResponses[keyof GetPublicBodyTypesResponses];

export type GetPublicBodyRelationshipsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/PublicBodies/relationships';
};

export type GetPublicBodyRelationshipsResponses = {
    /**
     * OK
     */
    200: AdrPublicBodiesModelsBaseResponseModelSystemCollectionsGenericListAdrPublicBodiesModelsPublicBodyParentChildModel;
};

export type GetPublicBodyRelationshipsResponse = GetPublicBodyRelationshipsResponses[keyof GetPublicBodyRelationshipsResponses];

export type GetPublicBodyHistoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/PublicBodies/{id}/history';
};

export type GetPublicBodyHistoryErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails | MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
};

export type GetPublicBodyHistoryError = GetPublicBodyHistoryErrors[keyof GetPublicBodyHistoryErrors];

export type GetPublicBodyHistoryResponses = {
    /**
     * OK
     */
    200: AdrPublicBodiesModelsBaseResponseModelAdrPublicBodiesModelsPublicBodyHistoryModel;
};

export type GetPublicBodyHistoryResponse = GetPublicBodyHistoryResponses[keyof GetPublicBodyHistoryResponses];
