// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zAdrPublicBodiesModelsBaseAuditModel = z.object({
    recordCreatedDatetime: z.iso.date().nullish(),
    recordEndedDatetime: z.iso.date().nullish(),
    recordCreatedUser: z.string().nullish(),
    recordEndedUser: z.string().nullish()
});

export const zAdrPublicBodiesModelsPublicBodyModel = zAdrPublicBodiesModelsBaseAuditModel.and(z.object({
    id: z.string().nullable(),
    staticId: z.string().nullable(),
    publicBodyId: z.string().nullish(),
    businessIdSource: z.string().nullish(),
    businessIdValue: z.string().nullish(),
    name: z.string().nullable(),
    acronym: z.string().nullish(),
    sector: z.string().nullish(),
    typeId: z.string().nullish(),
    publicBodyEffectiveDate: z.iso.date().nullish(),
    publicBodyRetiredDate: z.iso.date().nullish()
}));

/**
 * BaseResponseModel<PublicBodyModel>
 */
export const zAdrPublicBodiesModelsBaseResponseModelAdrPublicBodiesModelsPublicBodyModel = z.object({
    payload: zAdrPublicBodiesModelsPublicBodyModel,
    datetimeRequested: z.iso.datetime()
});

/**
 * BaseResponseModel<IEnumerable`1>
 */
export const zAdrPublicBodiesModelsBaseResponseModelSystemCollectionsGenericListAdrPublicBodiesModelsPublicBodyModel = z.object({
    payload: z.array(zAdrPublicBodiesModelsPublicBodyModel).nullable(),
    datetimeRequested: z.iso.datetime()
});

export const zAdrPublicBodiesModelsPublicBodyParentChildModel = zAdrPublicBodiesModelsBaseAuditModel.and(z.object({
    parentChildId: z.string().nullable(),
    actionDatetime: z.iso.date().nullish(),
    parentUniqueId: z.string().nullable(),
    childUniqueId: z.string().nullable(),
    wasRenamed: z.boolean().optional(),
    wasMerged: z.boolean().optional(),
    wasSplit: z.boolean().optional(),
    publicBodyEffectiveDatetime: z.iso.date().nullish()
}));

/**
 * BaseResponseModel<IEnumerable`1>
 */
export const zAdrPublicBodiesModelsBaseResponseModelSystemCollectionsGenericListAdrPublicBodiesModelsPublicBodyParentChildModel = z.object({
    payload: z.array(zAdrPublicBodiesModelsPublicBodyParentChildModel).nullable(),
    datetimeRequested: z.iso.datetime()
});

export const zAdrPublicBodiesModelsPublicBodyHistoryModel = z.object({
    publicBodyId: z.string().nullable(),
    publicBodies: z.array(zAdrPublicBodiesModelsPublicBodyModel).nullable(),
    relationships: z.array(zAdrPublicBodiesModelsPublicBodyParentChildModel).nullable()
});

/**
 * BaseResponseModel<PublicBodyHistoryModel>
 */
export const zAdrPublicBodiesModelsBaseResponseModelAdrPublicBodiesModelsPublicBodyHistoryModel = z.object({
    payload: zAdrPublicBodiesModelsPublicBodyHistoryModel,
    datetimeRequested: z.iso.datetime()
});

export const zAdrPublicBodiesModelsPublicBodyTypeModel = zAdrPublicBodiesModelsBaseAuditModel.and(z.object({
    id: z.string().nullable(),
    staticId: z.string().nullable(),
    publicBodyTypeId: z.string().nullish(),
    name: z.string().nullable(),
    shortName: z.string().nullish(),
    typeEffectiveDatetime: z.iso.date().nullish(),
    typeRetiredDatetime: z.iso.date().nullish()
}));

/**
 * BaseResponseModel<IEnumerable`1>
 */
export const zAdrPublicBodiesModelsBaseResponseModelSystemCollectionsGenericListAdrPublicBodiesModelsPublicBodyTypeModel = z.object({
    payload: z.array(zAdrPublicBodiesModelsPublicBodyTypeModel).nullable(),
    datetimeRequested: z.iso.datetime()
});

export const zMicrosoftAspNetCoreMvcProblemDetails = z.object({
    type: z.string().nullish(),
    title: z.string().nullish(),
    status: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    detail: z.string().nullish(),
    instance: z.string().nullish()
});

export const zMicrosoftAspNetCoreHttpHttpValidationProblemDetails = zMicrosoftAspNetCoreMvcProblemDetails.and(z.object({
    errors: z.record(z.string(), z.array(z.string())).nullish()
}));

export const zGetAllPublicBodiesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetAllPublicBodiesResponse = zAdrPublicBodiesModelsBaseResponseModelSystemCollectionsGenericListAdrPublicBodiesModelsPublicBodyModel;

export const zGetPublicBodyByIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetPublicBodyByIdResponse = zAdrPublicBodiesModelsBaseResponseModelAdrPublicBodiesModelsPublicBodyModel;

export const zGetPublicBodyTypesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetPublicBodyTypesResponse = zAdrPublicBodiesModelsBaseResponseModelSystemCollectionsGenericListAdrPublicBodiesModelsPublicBodyTypeModel;

export const zGetPublicBodyRelationshipsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetPublicBodyRelationshipsResponse = zAdrPublicBodiesModelsBaseResponseModelSystemCollectionsGenericListAdrPublicBodiesModelsPublicBodyParentChildModel;

export const zGetPublicBodyHistoryData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetPublicBodyHistoryResponse = zAdrPublicBodiesModelsBaseResponseModelAdrPublicBodiesModelsPublicBodyHistoryModel;
