// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAllDictionariesData, GetAllDictionariesResponses, GetAllGlossaryData, GetAllGlossaryResponses, GetGlossaryEntryByTermData, GetGlossaryEntryByTermErrors, GetGlossaryEntryByTermResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getAllDictionaries = <ThrowOnError extends boolean = false>(options?: Options<GetAllDictionariesData, ThrowOnError>) => (options?.client ?? client).get<GetAllDictionariesResponses, unknown, ThrowOnError>({ url: '/v1/Dictionary', ...options });

export const getAllGlossary = <ThrowOnError extends boolean = false>(options?: Options<GetAllGlossaryData, ThrowOnError>) => (options?.client ?? client).get<GetAllGlossaryResponses, unknown, ThrowOnError>({ url: '/v1/Glossary', ...options });

export const getGlossaryEntryByTerm = <ThrowOnError extends boolean = false>(options: Options<GetGlossaryEntryByTermData, ThrowOnError>) => (options.client ?? client).get<GetGlossaryEntryByTermResponses, GetGlossaryEntryByTermErrors, ThrowOnError>({ url: '/v1/Glossary/{term}', ...options });
