// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5001' | (string & {});
};

export type AdrSemanticsModelsBaseAuditModel = {
    /**
     * Nullable<DateTime>
     */
    recordCreatedDatetime?: string | null;
    /**
     * Nullable<DateTime>
     */
    recordEndedDatetime?: string | null;
    recordCreatedUser?: string | null;
    recordEndedUser?: string | null;
};

/**
 * BaseResponseModel<GlossaryModel>
 */
export type AdrSemanticsModelsBaseResponseModelAdrSemanticsModelsGlossaryModel = {
    payload: AdrSemanticsModelsGlossaryModel;
    datetimeRequested: string;
};

/**
 * BaseResponseModel<IEnumerable`1>
 */
export type AdrSemanticsModelsBaseResponseModelSystemCollectionsGenericListAdrSemanticsModelsDictionaryModel = {
    /**
     * IEnumerable<DictionaryModel>
     */
    payload: Array<AdrSemanticsModelsDictionaryModel> | null;
    datetimeRequested: string;
};

/**
 * BaseResponseModel<IEnumerable`1>
 */
export type AdrSemanticsModelsBaseResponseModelSystemCollectionsGenericListAdrSemanticsModelsGlossaryModel = {
    /**
     * IEnumerable<GlossaryModel>
     */
    payload: Array<AdrSemanticsModelsGlossaryModel> | null;
    datetimeRequested: string;
};

export type AdrSemanticsModelsDictionaryEntryFieldModel = AdrSemanticsModelsBaseAuditModel & {
    fieldName: string | null;
    fieldDescription: string | null;
    schemaNameTableName: string | null;
    dataSource: string | null;
    dataType: string | null;
    keyRelationships: string | null;
    systemOfRecord: string | null;
    designatedAsRequired: string | null;
    semanticTermRef: string | null;
};

export type AdrSemanticsModelsDictionaryEntryModel = AdrSemanticsModelsBaseAuditModel & {
    id: string | null;
    name: string | null;
    source: string | null;
    /**
     * IList<DictionaryEntryFieldModel>
     */
    fields?: Array<AdrSemanticsModelsDictionaryEntryFieldModel> | null;
};

export type AdrSemanticsModelsDictionaryModel = AdrSemanticsModelsBaseAuditModel & {
    id: string | null;
    /**
     * IList<DictionaryEntryModel>
     */
    entries?: Array<AdrSemanticsModelsDictionaryEntryModel> | null;
};

export type AdrSemanticsModelsGlossaryModel = AdrSemanticsModelsBaseAuditModel & {
    id?: string | null;
    name?: string | null;
    term: string | null;
    definition?: string | null;
    /**
     * IList<String>
     */
    keywords?: Array<string> | null;
    context?: string | null;
    citations?: string | null;
    teamSource?: string | null;
    verifiedDefinitionFlag?: boolean;
    publishToDevHub?: boolean;
};

export type MicrosoftAspNetCoreHttpHttpValidationProblemDetails = MicrosoftAspNetCoreMvcProblemDetails & {
    /**
     * IDictionary<String>
     */
    errors?: {
        [key: string]: Array<string>;
    } | null;
    [key: string]: unknown;
};

export type MicrosoftAspNetCoreMvcProblemDetails = {
    type?: string | null;
    title?: string | null;
    /**
     * Nullable<Int32>
     */
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type GetAllDictionariesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/Dictionary';
};

export type GetAllDictionariesResponses = {
    /**
     * OK
     */
    200: AdrSemanticsModelsBaseResponseModelSystemCollectionsGenericListAdrSemanticsModelsDictionaryModel;
};

export type GetAllDictionariesResponse = GetAllDictionariesResponses[keyof GetAllDictionariesResponses];

export type GetAllGlossaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/Glossary';
};

export type GetAllGlossaryResponses = {
    /**
     * OK
     */
    200: AdrSemanticsModelsBaseResponseModelSystemCollectionsGenericListAdrSemanticsModelsGlossaryModel;
};

export type GetAllGlossaryResponse = GetAllGlossaryResponses[keyof GetAllGlossaryResponses];

export type GetGlossaryMarkdownData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/Glossary/markdown';
};

export type GetGlossaryMarkdownResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetGlossaryMarkdownResponse = GetGlossaryMarkdownResponses[keyof GetGlossaryMarkdownResponses];

export type GetGlossaryMarkdownListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/Glossary/markdown-list';
};

export type GetGlossaryMarkdownListResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetGlossaryMarkdownListResponse = GetGlossaryMarkdownListResponses[keyof GetGlossaryMarkdownListResponses];

export type GetGlossaryEntryByTermData = {
    body?: never;
    path: {
        term: string;
    };
    query?: never;
    url: '/v1/Glossary/{term}';
};

export type GetGlossaryEntryByTermErrors = {
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails | MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
};

export type GetGlossaryEntryByTermError = GetGlossaryEntryByTermErrors[keyof GetGlossaryEntryByTermErrors];

export type GetGlossaryEntryByTermResponses = {
    /**
     * OK
     */
    200: AdrSemanticsModelsBaseResponseModelAdrSemanticsModelsGlossaryModel;
};

export type GetGlossaryEntryByTermResponse = GetGlossaryEntryByTermResponses[keyof GetGlossaryEntryByTermResponses];
