// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zAdrSemanticsModelsBaseAuditModel = z.object({
    recordCreatedDatetime: z.iso.datetime().nullish(),
    recordEndedDatetime: z.iso.datetime().nullish(),
    recordCreatedUser: z.string().nullish(),
    recordEndedUser: z.string().nullish()
});

export const zAdrSemanticsModelsDictionaryEntryFieldModel = zAdrSemanticsModelsBaseAuditModel.and(z.object({
    fieldName: z.string().nullable(),
    fieldDescription: z.string().nullable(),
    schemaNameTableName: z.string().nullable(),
    dataSource: z.string().nullable(),
    dataType: z.string().nullable(),
    keyRelationships: z.string().nullable(),
    systemOfRecord: z.string().nullable(),
    designatedAsRequired: z.string().nullable(),
    semanticTermRef: z.string().nullable()
}));

export const zAdrSemanticsModelsDictionaryEntryModel = zAdrSemanticsModelsBaseAuditModel.and(z.object({
    id: z.string().nullable(),
    name: z.string().nullable(),
    source: z.string().nullable(),
    fields: z.array(zAdrSemanticsModelsDictionaryEntryFieldModel).nullish()
}));

export const zAdrSemanticsModelsDictionaryModel = zAdrSemanticsModelsBaseAuditModel.and(z.object({
    id: z.string().nullable(),
    entries: z.array(zAdrSemanticsModelsDictionaryEntryModel).nullish()
}));

/**
 * BaseResponseModel<IEnumerable`1>
 */
export const zAdrSemanticsModelsBaseResponseModelSystemCollectionsGenericListAdrSemanticsModelsDictionaryModel = z.object({
    payload: z.array(zAdrSemanticsModelsDictionaryModel).nullable(),
    datetimeRequested: z.iso.datetime()
});

export const zAdrSemanticsModelsGlossaryModel = zAdrSemanticsModelsBaseAuditModel.and(z.object({
    id: z.string().nullish(),
    name: z.string().nullish(),
    term: z.string().nullable(),
    definition: z.string().nullish(),
    keywords: z.array(z.string()).nullish(),
    context: z.string().nullish(),
    citations: z.string().nullish(),
    teamSource: z.string().nullish(),
    verifiedDefinitionFlag: z.boolean().optional(),
    publishToDevHub: z.boolean().optional()
}));

/**
 * BaseResponseModel<GlossaryModel>
 */
export const zAdrSemanticsModelsBaseResponseModelAdrSemanticsModelsGlossaryModel = z.object({
    payload: zAdrSemanticsModelsGlossaryModel,
    datetimeRequested: z.iso.datetime()
});

/**
 * BaseResponseModel<IEnumerable`1>
 */
export const zAdrSemanticsModelsBaseResponseModelSystemCollectionsGenericListAdrSemanticsModelsGlossaryModel = z.object({
    payload: z.array(zAdrSemanticsModelsGlossaryModel).nullable(),
    datetimeRequested: z.iso.datetime()
});

export const zMicrosoftAspNetCoreMvcProblemDetails = z.object({
    type: z.string().nullish(),
    title: z.string().nullish(),
    status: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    detail: z.string().nullish(),
    instance: z.string().nullish()
});

export const zMicrosoftAspNetCoreHttpHttpValidationProblemDetails = zMicrosoftAspNetCoreMvcProblemDetails.and(z.object({
    errors: z.record(z.string(), z.array(z.string())).nullish()
}));

export const zGetAllDictionariesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetAllDictionariesResponse = zAdrSemanticsModelsBaseResponseModelSystemCollectionsGenericListAdrSemanticsModelsDictionaryModel;

export const zGetAllGlossaryData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetAllGlossaryResponse = zAdrSemanticsModelsBaseResponseModelSystemCollectionsGenericListAdrSemanticsModelsGlossaryModel;

export const zGetGlossaryMarkdownData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetGlossaryMarkdownResponse = z.string();

export const zGetGlossaryMarkdownListData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetGlossaryMarkdownListResponse = z.string();

export const zGetGlossaryEntryByTermData = z.object({
    body: z.never().optional(),
    path: z.object({
        term: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetGlossaryEntryByTermResponse = zAdrSemanticsModelsBaseResponseModelAdrSemanticsModelsGlossaryModel;
